#################################################################
# AI GUIDELINES
#
# This project requires AI/code-generators to follow these rules when
# creating or editing code in this repository:
#
# - Use these package versions for state & navigation libraries:
#     flutter_riverpod: ^2.6.1
#     flutter_bloc:    ^9.1.1
#     go_router:       ^16.1.0
# - UI code must follow Material 3 conventions (ThemeData(useMaterial3: true)).
# - Use `solar_icons` for icons in UI code.
# - When adding/changing UI files, reference templates under
#     dev/templates/ai-reference and include a `References:` line in PRs.
# - Do not copy templates verbatim; use them as reference only.
# - Pages/screens must be designed mobile-first ( prioritize touch, layout and performance for phones ),
#   and implemented responsively so they display well on PC/web as well.
#
# Place small, non-disruptive changes directly. For template updates,
# coordinate with repository admins (templates are protected).
#################################################################

name: bamstar
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.9.0

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  solar_icons: ^0.0.5
  just_the_tooltip: ^0.0.12
  animated_introduction: ^1.0.4
  animated_emoji: ^3.2.1
  delayed_display: ^2.0.0
  flutter_bloc: ^9.1.1
  flutter_riverpod: ^2.6.1
  go_router: ^16.1.0
  cached_network_image: ^3.4.1
  infinite_scroll_pagination: ^5.1.0
  avatar_stack: ^3.0.0
  badges: ^3.1.2
  banner_carousel: ^1.2.1
  smooth_page_indicator: ^1.2.1
  flutter_card_swiper: ^7.0.2
  skeletonizer: ^2.1.0+1
  flutter_secure_storage: ^9.2.4
  flutter_dotenv: ^5.1.0
  logging: ^1.3.0
  delightful_toast: ^1.1.0
  shared_preferences: ^2.5.3
  # font_awesome_flutter removed — project standard requires using solar_icons
  supabase_flutter: ^2.5.6
  choice: ^2.3.2
  sign_in_with_apple: ^7.0.1
  kakao_flutter_sdk_user: ^1.9.7+3
  kakao_flutter_sdk_common: ^1.9.7+3
  google_sign_in: ^7.1.1
  uuid: ^4.5.1
  animations: ^2.0.11
  firebase_core: ^3.15.0
  firebase_analytics: ^11.3.3
  firebase_messaging: ^15.2.10
  permission_handler: ^12.0.1
  flutter_gemini_bot: ^0.0.4
  flutter_gemini: ^3.0.0
  dio: ^5.9.0
  wolt_modal_sheet: ^0.11.0
  salomon_bottom_bar: ^3.3.2
  image_picker: ^1.2.0
  image_size_getter: ^2.1.3
  cloudinary_url_gen: ^1.8.0
  korean_profanity_filter: ^1.0.0
  google_mlkit_image_labeling: ^0.14.1
  flutter_html: ^3.0.0-beta.2
  drop_down_search_field: ^1.1.3
  visibility_detector: ^0.3.0
  kpostal: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
  - .env
  - assets/images/onboard/onboard_one.webp
  - assets/images/onboard/onboard_two.webp
  - assets/images/onboard/onboard_three.webp
  - assets/images/icon/
  - assets/images/avatar/
  - assets/images/banner/banner_01.png
  - assets/images/banner/banner_02.png
  - assets/images/banner/banner_03.png
  - assets/images/banner/banner_04.png
  - assets/images/banner/banner_05.png

  # Fonts: Pretendard (place Pretendard OTF/TTF files under assets/font/Pretendard/)
  # Please add the Pretendard font files with the names below, or tell me and
  # I can add placeholder files for testing.
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/font/Pretendard/Pretendard-Thin.otf
          weight: 100
        - asset: assets/font/Pretendard/Pretendard-ExtraLight.otf
          weight: 200
        - asset: assets/font/Pretendard/Pretendard-Light.otf
          weight: 300
        - asset: assets/font/Pretendard/Pretendard-Regular.otf
          weight: 400
        - asset: assets/font/Pretendard/Pretendard-Medium.otf
          weight: 500
        - asset: assets/font/Pretendard/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/font/Pretendard/Pretendard-Bold.otf
          weight: 700
        - asset: assets/font/Pretendard/Pretendard-ExtraBold.otf
          weight: 800
        - asset: assets/font/Pretendard/Pretendard-Black.otf
          weight: 900

# Launcher icon generation config
flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/icon/app_icon.png
  min_sdk_android: 21
  remove_alpha_ios: true
  adaptive_icon_background: "#FFFFFF"

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
