name: supabase-migrate

on:
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare Node runtime (npm available)
        shell: bash
        run: |
          set -euo pipefail
          echo "Ensuring Node/npm are available (npx may be used for other tasks)"
          node --version || (echo "Node.js is not installed on runner" && exit 1)
          npm --version || (echo "npm is not installed on runner" && exit 1)

      - name: Install psql client
        shell: bash
        run: |
          set -euo pipefail
          echo "Installing postgresql client (psql)"
          sudo apt-get update -y
          sudo apt-get install -y postgresql-client

      - name: Run migration SQL against Supabase (psql)
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
          PGSSLMODE: require
        shell: bash
        run: |
          set -euo pipefail
          echo "Running migration via psql using SUPABASE_DB_URL secret"
          if [ -z "${SUPABASE_DB_URL:-}" ]; then
            echo "Missing required secret SUPABASE_DB_URL (postgres connection string)" >&2
            exit 1
          fi

          # psql accepts a full connection string, run the SQL file
          echo "Applying: dev/supabase/migrations/20250816_init_users_roles_devices.sql"
          psql "$SUPABASE_DB_URL" -v ON_ERROR_STOP=1 -f dev/supabase/migrations/20250816_init_users_roles_devices.sql

      - name: Verify tables created (psql)
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
          PGSSLMODE: require
        shell: bash
        run: |
          set -euo pipefail
          echo "select table_name from information_schema.tables where table_schema = 'public' and table_name in ('roles','users','devices');" > /tmp/verify.sql
          if [ -z "${SUPABASE_DB_URL:-}" ]; then
            echo "Missing required secret SUPABASE_DB_URL (postgres connection string)" >&2
            exit 1
          fi
          echo "Verifying via psql"
          psql "$SUPABASE_DB_URL" -At -f /tmp/verify.sql
